- name: Set the hostname
  include_role:
    name: hostname
  when: hostname is defined

- name: Setup ssh
  include_role:
    name: ssh

- name: Add the tailscale key
  apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.gpg
    state: present

- name: Add the tailscale repo
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    state: present
  register: R_tailscale_repo
  retries: 3
  delay: 10
  until: R_tailscale_repo is not failed

- name: Add the git ppa
  apt_repository:
    repo: ppa:git-core/ppa
  register: R_git_repo
  retries: 3
  delay: 10
  until: R_git_repo is not failed

- name: Update all packages
  package:
    name: "*"
    state: latest
  register: R_update
  retries: 3
  delay: 10
  until: R_update is not failed

- name: Install base packages
  apt:
    state: latest
    update_cache: true
    name: "{{ base_packages }}"
  register: R_install
  retries: 3
  delay: 10
  until: R_install is not failed

- name: Install AWS CLI
  include_role:
    name: awscli
  when: ansible_architecture == "x86_64"
