- name: Add the tailscale key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ os_name }}.gpg
    state: present

- name: Add the tailscale repo
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu {{ os_name }} main
    state: present

- name: Add the git ppa
  apt_repository:
    repo: ppa:git-core/ppa

- name: Update all packages
  package:
    name: "*"
    state: latest
  register: R_apt_update
  retries: 3
  delay: 10
  until: R_apt_update is not failed

- name: Install base packages
  apt:
    state: latest
    update_cache: true
    name:
      - curl
      - git
      - htop
      - mosh
      - net-tools
      - snapd
      - tailscale
      - tar
      - unzip
      - wget
  register: R_apt_install
  retries: 3
  delay: 10
  until: R_apt_install is not failed

- name: Install jq
  get_url:
    url: "https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64"
    dest: "/usr/local/bin/jq"
    owner: root
    group: root
    mode: 0755

- name: Install AWS CLI
  block:
    - name: Download AWS CLI Zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /usr/local/src/awscli.zip
        owner: root
        group: root
        mode: 0744

    - name: Unarchive AWS CLI Zip
      unarchive:
        src: /usr/local/src/awscli.zip
        dest: /usr/local/src
        remote_src: True

    - name: Run AWS CLI Install
      command: /usr/local/src/aws/install --update

    - name: Cleanup AWS CLI Zip
      file:
        path: "/usr/local/src/awscli.zip"
        state: absent

    - name: Cleanup AWS CLI Folder
      file:
        path: "/usr/local/src/aws"
        state: absent
  when: ansible_architecture == "x86_64"
