- name: Add the eternal terminal ppa
  apt_repository:
    repo: ppa:jgmath2000/et

- name: Update all packages
  package:
    name: '*'
    state: latest

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - awscli
    - curl
    - et
    - git
    - htop
    - jq
    - snapd
    - tar
    - unzip
    - wget
