- name: Update all packages
  package:
    name: '*'
    state: latest

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - ec2-net-utils
    - git
    - htop
    - jq
    - tar
    - unzip
    - wget
