# https://github.com/cloudflare/cloudflared/releases
cloudflared_version: "2020.11.7"

cloudflared_name: cloudflared

cloudflared_log_path: /var/log/{{ cloudflared_name }}.log
cloudflared_bin_path: /usr/local/bin/{{ cloudflared_name }}
cloudflared_data_dir: /var/lib/{{ cloudflared_name }}
cloudflared_cert_path: "{{ cloudflared_data_dir }}/cert.pem"
cloudflared_config_path: "{{ cloudflared_data_dir }}/config.yml"

cloudflared_tunnel_uuid: ba6449e1-9ff4-4046-898c-07d6373404f6
cloudflared_tunnel_ingress: https://localhost:443
cloudflared_tunnel_no_tls_verify: "true" # cannot make certs for localhost
