- name: Create the adguard Group
  group:
    name: "{{ adguard_name }}"
    system: true

- name: Create the adguard User
  user:
    name: "{{ adguard_name }}"
    group: "{{ adguard_name }}"
    system: true
    createhome: false
    home: "{{ adguard_data_dir }}"
    shell: /sbin/nologin
    comment: service account to run {{ adguard_name }}

- name: Download adguard
  get_url:
    url: https://static.adguard.com/adguardhome/release/AdGuardHome_linux_arm.tar.gz
    dest: "{{ install_dir }}/adguard.tar.gz"
    mode: 0744
    owner: root
    group: root
  register: R_adguard_download

- name: Extract adguard
  unarchive:
    remote_src: true
    src: "{{ install_dir }}/adguard.tar.gz"
    dest: "{{ install_dir }}"
  when: R_adguard_download.changed

- name: Copy adguard binary
  copy:
    remote_src: true
    src: "{{ install_dir }}/AdGuardHome/AdGuardHome"
    dest: "{{ adguard_bin_path }}"
    mode: 0755
    owner: root
    group: root
  when: R_adguard_download.changed

- name: Cleanup adguard
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ install_dir }}/AdGuardHome"
