vault_version: 1.5.3
vault_version_checksum: 1ec61ff4d0b7ed774ba6f71829596afd8c8bf1d72c97305f4692001cef8910b2

vault_name: vault
vault_bin_path: /usr/local/bin/{{ vault_name }}
vault_config_dir: /var/lib/{{ vault_name }}
vault_server_log_path: /var/log/vault-server.log
vault_audit_log_path: /var/log/vault-audit.log
