- name: allow ip forwarding
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.forwarding
    - net.ipv6.conf.all.forwarding
  when:
    - ansible_virtualization_type != "docker"
