- name: Configure ssh
  block:
    - name: Enable ssh
      service:
        name: ssh
        enabled: true

    - name: Start ssh
      service:
        name: ssh
        state: started

    - name: Add ssh keys
      template:
        src: authorized_keys.j2
        dest: /home/ubuntu/.ssh/authorized_keys
        mode: 0600
        owner: ubuntu
        group: ubuntu

- name: Install traefik
  block:
    - name: Download traefik
      get_url:
        url: https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_linux_arm64.tar.gz
        dest: /usr/local/src/traefik.tar.gz
        mode: 0744
        owner: root
        group: root

    - name: Extract traefik
      unarchive:
        remote_src: true
        src: /usr/local/src/traefik.tar.gz
        dest: /usr/local/src

    - name: Copy traefik binary
      copy:
        remote_src: true
        src: /usr/local/src/traefik
        dest: /usr/local/bin/traefik
        mode: 0755
        owner: root
        group: root

    - name: Cleanup traefik
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/src/traefik
        - /usr/local/src/traefik.tar.gz

- name: Install adguard
  block:
    - name: Download adguard
      get_url:
        url: https://static.adguard.com/adguardhome/release/AdGuardHome_linux_arm.tar.gz
        dest: /usr/local/src/adguard.tar.gz
        mode: 0744
        owner: root
        group: root

    - name: Extract adguard
      unarchive:
        remote_src: true
        src: /usr/local/src/adguard.tar.gz
        dest: /usr/local/src

    - name: Copy adguard binary
      copy:
        remote_src: true
        src: /usr/local/src/AdGuardHome/AdGuardHome
        dest: /usr/local/bin/adguard
        mode: 0755
        owner: root
        group: root

    - name: Cleanup adguard
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/src/adguard.tar.gz
        - /usr/local/src/AdGuardHome

- name: Configure adguard
  block:
    - name: Create adguard directory
      file:
        state: directory
        path: /var/lib/adguard
        mode: 0700
        owner: root
        group: root

    - name: Copy adguard service file
      copy:
        src: adguard.service
        dest: /etc/systemd/system/adguard.service
        mode: 0644
        owner: root
        group: root

    - name: Enable adguard
      service:
        name: adguard
        enabled: true

    - name: Stop adguard
      service:
        name: adguard
        state: stopped

    # adguard must be stopped to prevent overwrites
    - name: Copy adguard config file
      template:
        src: adguard_config.yaml.j2
        dest: /var/lib/adguard/config.yaml
        mode: 0600
        owner: root
        group: root

    - name: Start adguard
      service:
        name: adguard
        state: started
