- name: Install traefik
  include_role:
    name: traefik

- name: Configure traefik
  block:
    - name: Create traefik data directory
      file:
        state: directory
        path: "{{ traefik_data_dir }}"
        mode: 0775
        owner: root
        group: "{{ traefik_name }}"

    - name: Create traefik dynamic directory
      file:
        state: directory
        path: "{{ traefik_dynamic_dir }}"
        mode: 0775
        owner: root
        group: "{{ traefik_name }}"

    - name: Copy traefik config file
      template:
        src: traefik.yml.j2
        dest: "{{ traefik_config_path }}"
        mode: 0644
        owner: root
        group: "{{ traefik_name }}"

    - name: Copy traefik dynamic file
      template:
        src: traefik_dynamic.yml.j2
        dest: "{{ traefik_dynamic_dir }}/dynamic.yml"
        mode: 0644
        owner: root
        group: "{{ traefik_name }}"

    - name: Create traefik acme file
      file:
        state: touch
        path: "{{ traefik_acme_path }}"
        mode: 0600
        owner: "{{ traefik_name }}"
        group: "{{ traefik_name }}"
        access_time: preserve
        modification_time: preserve

    - name: Create traefik log files
      file:
        state: touch
        path: "{{ item }}"
        mode: 0664
        owner: root
        group: "{{ traefik_name }}"
        access_time: preserve
        modification_time: preserve
      loop:
        - "{{ traefik_log_path }}"
        - "{{ traefik_access_log_path }}"

    - name: Copy traefik environment file
      template:
        src: traefik_env.j2
        dest: /etc/default/{{ traefik_name }}
        mode: 0400
        owner: "{{ traefik_name }}"
        group: "{{ traefik_name }}"

    - name: Copy traefik service file
      template:
        src: traefik.service.j2
        dest: /etc/systemd/system/{{ traefik_name }}.service
        mode: 0644
        owner: root
        group: root

    - name: Enable traefik
      service:
        name: "{{ traefik_name }}"
        enabled: true

    # - name: Start traefik
    #   service:
    #     name: "{{ traefik_name }}"
    #     state: started

- name: Install adguard
  include_role:
    name: adguard

- name: Configure adguard
  block:
    - name: Create adguard data directory
      file:
        state: directory
        path: "{{ adguard_data_dir }}"
        mode: 0775
        owner: root
        group: "{{ adguard_name }}"

    - name: Create adguard log files
      file:
        state: touch
        path: "{{ item }}"
        mode: 0664
        owner: root
        group: "{{ adguard_name }}"
        access_time: preserve
        modification_time: preserve
      loop:
        - "{{ adguard_log_path }}"

    - name: Copy adguard service file
      template:
        src: adguard.service.j2
        dest: /etc/systemd/system/{{ adguard_name }}.service
        mode: 0644
        owner: root
        group: root

    - name: Enable adguard
      service:
        name: "{{ adguard_name }}"
        enabled: true

    # TODO - Only stop adguard if file will change
    # adguard must be stopped to prevent config overwrites
    - name: Stop adguard
      service:
        name: "{{ adguard_name }}"
        state: stopped

    - name: Copy adguard config file
      template:
        src: adguard_config.yaml.j2
        dest: "{{ adguard_config_path }}"
        mode: 0664
        owner: root
        group: "{{ adguard_name }}"
    # - name: Start adguard
    #   service:
    #     name: "{{ adguard_name }}"
    #     state: started
