- name: Download
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
    dest: "{{ install_dir }}/awscli.zip"
    owner: root
    group: root
    mode: 0744

- name: Unarchive
  unarchive:
    src: "{{ install_dir }}/awscli.zip"
    dest: "{{ install_dir }}"
    remote_src: true
    mode: 0744
  register: R_unarchive

- name: Install
  command: "{{ install_dir }}/aws/install --update"
  when: R_unarchive.changed

- name: Cleanup
  file:
    path: "{{ install_dir }}/aws"
    state: absent
