- name: Require x86_64 architecture
  fail:
    msg: "awscli v2 only supports x86_64 architecture"
  when: ansible_architecture != "x86_64"

- name: Download
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ install_dir }}/awscli.zip"
    owner: root
    group: root
    mode: 0744

- name: Unarchive
  unarchive:
    src: "{{ install_dir }}/awscli.zip"
    dest: "{{ install_dir }}"
    remote_src: true

- name: Install
  command: "{{ install_dir }}/aws/install --update"

- name: Cleanup
  file:
    path: "{{ install_dir }}/aws"
    state: absent
