- name: Require hostname variable to be set
  fail:
    msg: "variable `hostname` must be set"
  when: (hostname == "") or (hostname == "FAIL")

- name: Set Hostname
  hostname:
    name: "{{ hostname }}"

- name: Resolve hostname to localhost
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ hostname }}"
    mode: 0644
    owner: root
    group: root
