- name: Create the traefik Group
  group:
    name: "{{ traefik_name }}"
    system: true

- name: Create the traefik User
  user:
    name: "{{ traefik_name }}"
    group: "{{ traefik_name }}"
    system: true
    createhome: false
    home: "{{ traefik_data_dir }}"
    shell: /sbin/nologin
    comment: service account to run {{ traefik_name }}

# Keep the download on the system for idempotency
- name: Download traefik
  get_url:
    url: https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_linux_arm64.tar.gz
    dest: "{{ install_dir }}/traefik.tar.gz"
    mode: 0744
    owner: root
    group: root
  register: R_traefik_download

- name: Extract traefik
  unarchive:
    remote_src: true
    src: "{{ install_dir }}/traefik.tar.gz"
    dest: "{{ install_dir }}"
  when: R_traefik_download.changed

- name: Copy traefik binary
  copy:
    remote_src: true
    src: "{{ install_dir }}/traefik"
    dest: "{{ traefik_bin_path }}"
    mode: 0755
    owner: root
    group: root
  when: R_traefik_download.changed

- name: Cleanup traefik
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ install_dir }}/traefik"
