- name: Update all packages
  package:
    name: '*'
    state: latest

- name: Install necessary packages
  apt:
    state: latest
    update_cache: yes
    name:
      - net-tools
      - qrencode
      - wireguard

- name: allow ip forwarding
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.forwarding
    - net.ipv6.conf.all.forwarding

- name: Create the wireguard directory
  file:
    state: directory
    path: /etc/wireguard
    owner: root
    group: root
    mode: 0700

- name: Write the wireguard wg0 config file
  copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
