- name: Update all packages
  package:
    name: "*"
    state: latest
  register: R_apt_update
  retries: 3
  delay: 10
  until: R_apt_update is not failed

- name: Install necessary packages
  apt:
    state: latest
    update_cache: true
    name:
      - net-tools
      - qrencode
      - wireguard
  register: R_apt_install
  retries: 3
  delay: 10
  until: R_apt_install is not failed

- name: allow ip forwarding
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.forwarding
    - net.ipv6.conf.all.forwarding
  when:
    - ansible_virtualization_type != "docker"

- name: Create the wireguard directory
  file:
    state: directory
    path: /etc/wireguard
    owner: root
    group: root
    mode: 0700

- name: Write the wireguard wg0 config file
  copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
