- name: create the vault group
  group:
    name: "{{ vault_name }}"
    system: true

- name: create the vault user
  user:
    name: "{{ vault_name }}"
    group: "{{ vault_name }}"
    system: true
    createhome: false
    home: "{{ vault_config_dir }}"
    shell: /sbin/nologin
    comment: service account to run vault

- name: download vault
  get_url:
    url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
    dest: /usr/local/src/vault_{{ vault_version }}_linux_amd64.zip
    owner: root
    group: root
    mode: 0744
    checksum: sha256:{{ vault_version_checksum }}

- name: unarchive vault zip
  unarchive:
    src: /usr/local/src/vault_{{ vault_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    mode: 0744

- name: set permissions on vault binary
  file:
    path: "{{ vault_bin_path }}"
    state: file
    owner: root
    group: root
    mode: 0755

- name: remove vault zip
  file:
    path: /usr/local/src/vault_{{ vault_version }}_linux_amd64.zip
    state: absent

- name: create vault config directory
  file:
    path: "{{ vault_config_dir }}"
    state: directory
    owner: root
    group: vault
    mode: 0750

- name: create vault audit log file
  file:
    path: "{{ vault_audit_log_path }}"
    state: touch
    owner: vault
    group: vault
    mode: "0200"

- name: add the vault service file
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644

- name: add vault global env vars
  copy:
    src: profile_vault.sh.j2
    dest: /etc/profile.d/vault.sh
    owner: root
    group: root
    mode: 0644

- name: allow vault to lock memory
  capabilities:
    state: present
    path: "{{ vault_bin_path }}"
    capability: cap_ipc_lock=+ep
