- name: Setup Raspberry Pi
  hosts: pis
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: interactive, tags: ["interactive"] }
    - { role: pi, tags: ["pi"] }
