- name: Setup Raspberry Pi
  hosts: pis
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Setup base requirements
      include_role:
        name: base
      tags: base
    - name: Setup for interactive
      include_role:
        name: interactive
      tags: interactive
    - name: Setup Raspberry Pi
      include_role:
        name: pi
      tags: pi
