# This playbook is run by packer
- name: Setup wireguard
  hosts: wireguard
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Setup base requirements
      include_role:
        name: base
      tags: base
    - name: Setup wireguard
      include_role:
        name: wireguard
      tags: wireguard
    - name: Cleanup
      include_role:
        name: cleanup
      tags: cleanup
