name: Packer - Validate

on:
  push:
    paths:
      - packer/**
      - ansible/**

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Ansible Lint
        run: ansible-lint ansible/**/*.yml
      # - name: Packer Validate
      #   run: packer validate infra.json
      #   working-directory: ./packer
