name: Packer - Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packer/**
      - ansible/**
  schedule:
    - cron: 0 16 * * 1 # Every Monday at 4pm UTC

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packer
        run: |
          wget -q https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -O /tmp/packer.zip
          sudo unzip -o /tmp/packer.zip -d /usr/local/bin
          sudo chown root:root /usr/local/bin/packer
          sudo chmod 755 /usr/local/bin/packer
          rm -f /tmp/packer.zip
        env:
          PACKER_VERSION: 1.6.4 # https://www.packer.io/downloads.html
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Ansible Lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible/**/*.yml
      - name: Packer Validate
        run: packer validate infra.pkr.hcl
        working-directory: ./packer
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account-id: ["038361916180", "840856573771"]
      fail-fast: false
    steps:
      - name: Install Packer
        run: |
          wget -q https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -O /tmp/packer.zip
          sudo unzip -o /tmp/packer.zip -d /usr/local/bin
          sudo chown root:root /usr/local/bin/packer
          sudo chmod 755 /usr/local/bin/packer
          rm -f /tmp/packer.zip
        env:
          PACKER_VERSION: 1.6.4 # https://www.packer.io/downloads.html
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: AWS Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_USER }}
          role-to-assume: arn:aws:iam::${{ matrix.account-id }}:role/ServiceAdmin
          role-session-name: GitHubActions
          role-duration-seconds: 1800
      - name: Packer Build
        run: packer build -only 'amazon-ebs.*' infra.pkr.hcl
        working-directory: ./packer
