name: Packer - Validate

on:
  workflow_dispatch:
  push:
    paths:
      - packer/**
      - ansible/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packer
        run: |
          wget -q https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -O /tmp/packer.zip
          sudo unzip -o /tmp/packer.zip -d /usr/local/bin
          sudo chown root:root /usr/local/bin/packer
          sudo chmod 755 /usr/local/bin/packer
          rm -f /tmp/packer.zip
        env:
          PACKER_VERSION: 1.6.5 # https://www.packer.io/downloads.html
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Ansible Lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible/**/*.yml
      - name: Packer Validate
        run: packer validate infra.pkr.hcl
        working-directory: ./packer
