name: Serverless - Validate

on:
  push:
    paths:
      - serverless/**

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go Format
        run: test -z $(gofmt -l -w -s ./)
