name: Serverless - Deploy

on:
  push:
  #   branches:
  #     - master
  #   paths:
  #     - serverless/**
  # schedule:
  #   - cron: 0 16 * * 1 # Every Monday at 4pm UTC

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go Format
        run: test -z $(gofmt -l -w -s ./...)
      - name: GolangCI Lint
        run: for d in ./*/ ; do (cd "$d" && golangci-lint run); done
        working-directory: ./serverless
  deploy-snsnotifier:
    needs: validate
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    strategy:
      matrix:
        account-id: ["418875065733"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: AWS Assume Role
        run: |
          role=$(aws sts assume-role --role-arn "arn:aws:iam::${{ matrix.account-id }}:role/ServiceAdmin" --role-session-name "GitHubActions")
          echo "export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<<$role)" > assume.sh
          echo "export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<<$role)" >> assume.sh
          echo "export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<<$role)" >> assume.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_USER }}
      - name: Deploy SNS Notifier
        run: eval "$(cat assume.sh)" && make deploy
        working-directory: ./serverless/sns-notifier
  deploy-amicleaner:
    needs: validate
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    strategy:
      matrix:
        account-id: ["418875065733", "038361916180", "840856573771"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: AWS Assume Role
        run: |
          role=$(aws sts assume-role --role-arn "arn:aws:iam::${{ matrix.account-id }}:role/ServiceAdmin" --role-session-name "GitHubActions")
          echo "export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId <<<$role)" > assume.sh
          echo "export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey <<<$role)" >> assume.sh
          echo "export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken <<<$role)" >> assume.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_USER }}
      - name: Deploy AMI Cleaner
        run: eval "$(cat assume.sh)" && make deploy
        working-directory: ./serverless/ami-cleaner
