name: Serverless - Validate

on:
  push:
    paths:
      - serverless/**

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Go Format
        run: test -z $(gofmt -l -w -s ./...)
      - name: GolangCI Lint
        run: for d in ./*/ ; do (cd "$d" && golangci-lint run); done
        working-directory: ./serverless
