name: Terraform - Validate

on:
  workflow_dispatch:
  push:
    paths:
      - terraform/**
      - terraform-modules/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Terraform Format
        run: terraform fmt -check -diff -recursive
