name: Validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Terraform Format Check
        run: terraform fmt -check -diff -recursive
